language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  - go get github.com/mattn/goveralls # for profiling coverage

install:
  - go mod download

script:
  - go test -v ./...
  - goveralls -service=travis-ci

jobs:
  include:
    - stage: acceptance
      if: type != pull_request and branch = master
      go: 1.12.x
      env:
        - GO111MODULE=on
        - TF_ACC=1
        - TF_VAR_ASSIGNEE_TICKET_FIELD_ID=360017262272
        - TF_VAR_DESCRIPTION_TICKET_FIELD_ID=360017262172
        - TF_VAR_GROUP_TICKET_FIELD_ID=360017262252
        - TF_VAR_STATUS_TICKET_FIELD_ID=360017262192
        - TF_VAR_SUBJECT_TICKET_FIELD_ID=360017262152
        - ZENDESK_ACCEPTANCE_TEST_ACCOUNT="d3v-terraform-provider"
        - secure: "Yt2MXtS9VoLzHdWYT/+RapyWM0DlgRVfAtmsP7gnOsj20HSDpTA2FO0fikz8gGCKAtWY5ZHfYDxTPn1xVxcydv8coYAbnKLbuFITWZn5p5DRhnxHO01GcnzebSFfjNDAH1ULkvMf2C+wlLxqafxrQz/Wt7ntbnFV6Ducyqlsl9hWeNZlrrqnuG2WQN55/D4Vzam09KFZ+a5gJPJKQ7hJGb/EEm6WnzEdgcX9NvI0J6jLwj4Ve1MOLibqIcnK/GSil33Ge82iBTJoc3zuG9I/EiuUq9Hbt/M+D1+1E9+zF5sokHtISHJ4ENmY/pgPJu7dKEeS6uXZc4VuTZJ/0fHl9cdAGoIqxOK26dh9McOEyCRzojX9SSEd00uFgP8dH5Fm11Pl3hi6Bw2WMx+UvG2nQTMgIq6cb6dbbs0SrOi0hEK+JuErXAJbIdQAnhHU72q43vIeZHqPtMcZ/5zHzuscn1kg2+Qwv4a6CJV1IfDBUOWIuQXr3X4sm/G5CF0JVZtf1C2JTzXp1wlXWV0mrQgQdH4Z1PdnTwHOCgbdwxvKkKUZezTAQAxIZTzcI//Sd8MTNVn6qaBbnduGnIK2r3eI2+S34AYq2iw/3X3hap1w4uOBiFuBO/5h8eVYyNyWC4CxGP4ghkpjKKleUkMQHF8UZlQaeCxXkqej0mtah/Lwi+s="
        - secure: "a6mUpYJWdfPgs3O52oeu56VRMHsDucX+9foQRy3Dz5JYJzsM6bexuyr9Vk9jA0mt4KaOdpzKDC+Vr25cl6vbIUkRXnmrqBuUpQbVWKt9rSdeaSoot63oImkw+MDOnis0yRAifNK/59jlyaOPlKLbbOshcSOkuenQUUMj2XL04S6k8sCAC8FxyScibJJJ+c52pPf5ByfLn41+BMjf5m1sU8JQQdI2zdA7asujmbiAyTfrg3iLFzHVh3UJLVmoKu7H6obkPEiGS0GtQU48Q8GDaqcfWKQOhDw2ORBRccprsy7FTWJlfaFd1nCCsOxdB0K8zGaPWCmcAjL0fxbYsYpdjAaILEUBl41C26cHWxg2nxndz1D9rXyTcVUXctOMXdNAdvWHGO5ejYyXd2/i+X800ftjuaNarFNe1L+alG568kfZBgYIQttMJOK32QGuxSAxbWgBP9+1NncEDcNCv5dJUKyLriIlPYEOutZsC3OUu47Q1kq578TyJZU+mlbRiUgoGwBm9gkk70lRFIt0kaoEjhyQBQkZQP4mTI74yIXqPSL1eVTjLyIdV7QIVIrQUjVfZsXitTvXTM5DWidrXi+NpzuI3Ihaj5qn55aqaYbXCCTRuG8XVkEhk9ZB0IGHypZGJnSVHvQMV1/XPIhNm/C9a4ztTz+6OgVttUY6DI6zeI8="
      script:
        - go test -v -cover -coverprofile=coverage.out -run TestAcc.* ./...
        - goveralls -coverprofile=coverage.out -service=travis-ci
      after_success:
        - curl -X POST $DOCKERHUB_TRIGGER_ENDPOINT

before_deploy:
  - go get github.com/mitchellh/gox
  - gox -os="linux darwin windows" -arch="386 amd64" -output="{{.Dir}}-{{.OS}}-{{.Arch}}/{{.Dir}}"
  - |
      for os in linux darwin windows; do
        for arch in 386 amd64; do
          cp README.md LICENSE terraform-provider-zendesk-$os-$arch
          zip -r terraform-provider-zendesk-$os-$arch.zip terraform-provider-zendesk-$os-$arch
        done
      done

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: terraform-provider-zendesk-*-*.zip
  skip_cleanup: true
  on:
    tags: true
    go: "1.11.x"

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ee2368b1378e7ade98d
    on_success: change
    on_failure: always
    on_start: never
